-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 0015: Calendar Domain
--
-- Three tables:
--   calendars       — bookable calendars per tenant, configurable via JSONB
--   calendar_slots  — pre-computed available/blocked time windows
--   appointments    — confirmed bookings (FK to conversation for traceability)
--
-- Concurrency strategy:
--   Slot booking uses SELECT FOR UPDATE on calendar_slots WHERE status='available'
--   so only one transaction can claim a slot at a time. The calendarService
--   wraps this in a transaction and rolls back on concurrent claims.
--
-- External integrations (Google Calendar, Outlook) are stored in calendars.config:
--   { "provider": "google", "credentials": {...}, "sync": true }
--   The calendarService checks provider and calls the appropriate adapter.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- Install btree_gist FIRST — needed for the EXCLUDE constraint on calendar_slots.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ── calendars ─────────────────────────────────────────────────────────────────
-- config JSONB:
--   {
--     "working_hours":    { "mon": ["09:00","18:00"], "tue": ["09:00","18:00"], ... },
--     "slot_duration_min": 30,
--     "buffer_min":        5,
--     "advance_days":      14,
--     "max_per_day":       8,
--     "provider":         "internal",          -- "internal" | "google" | "outlook"
--     "provider_credentials": {},              -- encrypted at app layer
--     "sync":             false
--   }
CREATE TABLE "calendars" (
    "id"         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    "tenant_id"  UUID         NOT NULL,
    "name"       VARCHAR(200) NOT NULL,
    "timezone"   VARCHAR(60)  NOT NULL DEFAULT 'America/Mexico_City',
    "activo"     BOOLEAN      NOT NULL DEFAULT TRUE,
    "config"     JSONB        NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT "calendars_tenant_id_fkey"
        FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

CREATE INDEX "idx_calendars_tenant_activo"
    ON "calendars" ("tenant_id", "activo");

CREATE INDEX "idx_calendars_config_gin"
    ON "calendars" USING GIN ("config" jsonb_path_ops);


-- ── calendar_slots ────────────────────────────────────────────────────────────
-- Materialised availability windows. Generated by the calendarService based on
-- calendars.config (working_hours + slot_duration_min).
--
-- Locking note: to book a slot atomically:
--   BEGIN;
--   SELECT id FROM calendar_slots
--     WHERE id = $1 AND status = 'available'
--     FOR UPDATE NOWAIT;       -- raises lock error immediately if contended
--   UPDATE calendar_slots SET status = 'booked', appointment_id = $2 WHERE id = $1;
--   COMMIT;
-- This prevents double-booking without an application-level mutex.
CREATE TABLE IF NOT EXISTS "calendar_slots" (
    "id"             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    "calendar_id"    UUID        NOT NULL,
    "start_time"     TIMESTAMPTZ NOT NULL,
    "end_time"       TIMESTAMPTZ NOT NULL,
    "status"         VARCHAR(20) NOT NULL DEFAULT 'available',
    "appointment_id" UUID,
    "created_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT "calendar_slots_calendar_id_fkey"
        FOREIGN KEY ("calendar_id") REFERENCES "calendars"("id") ON DELETE CASCADE
);

-- Primary availability query: get open slots in date range for a calendar
CREATE INDEX IF NOT EXISTS "idx_slots_calendar_status_start"
    ON "calendar_slots" ("calendar_id", "status", "start_time");

-- Time-range queries for a calendar
CREATE INDEX IF NOT EXISTS "idx_slots_calendar_time_range"
    ON "calendar_slots" ("calendar_id", "start_time", "end_time");

-- Lookup from appointment → its slots (for reschedule/cancel)
CREATE INDEX IF NOT EXISTS "idx_slots_appointment"
    ON "calendar_slots" ("appointment_id")
    WHERE "appointment_id" IS NOT NULL;


-- ── appointments ──────────────────────────────────────────────────────────────
-- One row per booking. Linked to:
--   • tenant    (for multi-tenant isolation)
--   • calendar  (which calendar was booked)
--   • conversation (which conversational session created this booking — for timeline)
--
-- metadata JSONB:
--   {
--     "user_name":         "Juan García",
--     "notes":             "Primera consulta",
--     "reminder_sent":     false,
--     "external_event_id": "google_evt_xyz",
--     "rescheduled_from":  "prev_appointment_uuid"
--   }
CREATE TABLE "appointments" (
    "id"              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    "tenant_id"       UUID        NOT NULL,
    "conversation_id" UUID,
    "user_key"        VARCHAR(120) NOT NULL,
    "calendar_id"     UUID        NOT NULL,
    "start_time"      TIMESTAMPTZ NOT NULL,
    "end_time"        TIMESTAMPTZ NOT NULL,
    "status"          VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    "metadata"        JSONB       NOT NULL DEFAULT '{}',
    "created_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT "appointments_tenant_id_fkey"
        FOREIGN KEY ("tenant_id")       REFERENCES "tenants"("id")       ON DELETE CASCADE,
    CONSTRAINT "appointments_calendar_id_fkey"
        FOREIGN KEY ("calendar_id")     REFERENCES "calendars"("id")     ON DELETE CASCADE,
    CONSTRAINT "appointments_conversation_id_fkey"
        FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE SET NULL
);

-- Dashboard: list appointments for a tenant by status / date
CREATE INDEX "idx_appts_tenant_status_start"
    ON "appointments" ("tenant_id", "status", "start_time" DESC);

-- Check existing appointments for a calendar window
CREATE INDEX "idx_appts_calendar_start"
    ON "appointments" ("calendar_id", "start_time");

-- User appointment history
CREATE INDEX "idx_appts_tenant_user_start"
    ON "appointments" ("tenant_id", "user_key", "start_time" DESC);

-- Traceability: which conversation created the appointment
CREATE INDEX "idx_appts_conversation"
    ON "appointments" ("conversation_id")
    WHERE "conversation_id" IS NOT NULL;

-- GIN for metadata search (reminder_sent, external_event_id, etc.)
CREATE INDEX "idx_appts_metadata_gin"
    ON "appointments" USING GIN ("metadata" jsonb_path_ops);

-- ─────────────────────────────────────────────────────────────────────────────
-- Install btree_gist for the EXCLUDE constraint on calendar_slots.
-- Already installed above — this block is kept as a no-op for clarity.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- Useful queries (comments only — not executed)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Get available slots for a calendar in the next 5 days:
--    SELECT id, start_time, end_time
--    FROM calendar_slots
--    WHERE calendar_id = '<uuid>'
--      AND status = 'available'
--      AND start_time >= NOW()
--      AND start_time <  NOW() + INTERVAL '5 days'
--    ORDER BY start_time
--    LIMIT 20;

-- 2. Book a slot (single transaction):
--    BEGIN;
--    SELECT id FROM calendar_slots WHERE id='<slot_uuid>' AND status='available' FOR UPDATE NOWAIT;
--    UPDATE calendar_slots SET status='booked', appointment_id='<appt_uuid>' WHERE id='<slot_uuid>';
--    INSERT INTO appointments (...) VALUES (...);
--    COMMIT;

-- 3. Appointments dashboard for a tenant:
--    SELECT a.id, a.user_key, a.status, a.start_time, a.end_time,
--           c.name AS calendar_name
--    FROM appointments a
--    JOIN calendars c ON c.id = a.calendar_id
--    WHERE a.tenant_id = '<uuid>'
--      AND a.start_time >= NOW()
--    ORDER BY a.start_time;

-- 4. Cancel appointment and free the slot:
--    BEGIN;
--    UPDATE appointments SET status='cancelled', updated_at=NOW() WHERE id='<uuid>';
--    UPDATE calendar_slots SET status='available', appointment_id=NULL WHERE appointment_id='<uuid>';
--    COMMIT;

-- 5. Double-booking check (should return 0 rows if EXCLUDE constraint works):
--    SELECT count(*) FROM calendar_slots
--    WHERE calendar_id='<uuid>' AND status='booked'
--    GROUP BY tstzrange(start_time, end_time, '[)')
--    HAVING count(*) > 1;
